### ISSUE TITLE
"sqlite3.OperationalError: database is locked" when running Mariposa in `single` mode

### ISSUE THREAD

**Issue by tenzinhl** [secure-foundations/mariposa#16]
Running Mariposa on one of the `smt2` files generated by `verus` for the `verisplinter` project.

Mariposa source commit: `71588d365a0d8803176828965d52e70fccdb389c`

Here's how I'm invoking Mariposa:
```
python3 scripts/main.py single -s z3_4_12_2 -q /home/tenzinhl/research/verification/verified-betrfs/Splinter/src/.verus-log/betree__PivotBranchRefinement_v.smt2
```
Attached is the SMT2 file that I'm running mariposa on:
[betree__PivotBranchRefinement_v.smt2.txt](https://github.com/secure-foundations/mariposa/files/14454058/betree__PivotBranchRefinement_v.smt2.txt)

This then leads to multiple of these `sqlite3.OperationalError: database is locked` exception messages after some delay. I think the process continues to progress, but it's hard to tell. It seems to be exacerbated by the fact that there's 40 original  queries for the file I'm running `single` mode on?
```
Traceback (most recent call last):
  File "/home/tenzinhl/.pyenv/versions/3.8.10/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/tenzinhl/.pyenv/versions/3.8.10/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/tenzinhl/research/verification/mariposa/scripts/runner.py", line 188, in run_tasks
    task.run()
  File "/home/tenzinhl/research/verification/mariposa/scripts/runner.py", line 149, in run
    self.run_solver(mutant_path)
  File "/home/tenzinhl/research/verification/mariposa/scripts/runner.py", line 124, in run_solver
    self.save_result_to_db(mutant_path, self.perturb, command, rcode, out, err, elapsed)
  File "/home/tenzinhl/research/verification/mariposa/scripts/runner.py", line 44, in save_result_to_db
    cur.execute(f"""INSERT INTO {self.exp_tname}
sqlite3.OperationalError: database is locked
```

Quick googling suggests that this can potentially be alleviated by extending the sqlite connection timeout, or by making better use of the Python sqlite3 API. That being said, overall it's unclear to me where the bottleneck is that's causing these timeouts. (Does the Rust code interact with sqlite?)

**Comment by yizhou7** [comment]
Thanks, that is a somewhat known but rare issue. 
I think it might happen when there are more worker processes than the number of physical cores.

I extended the db connection timeout, and introduced a retry when insertion fails in this commit: 
https://github.com/secure-foundations/mariposa/commit/13c3c42dddfb8a15ac9f877777a5201966d8d212

It won't prevent the problem, but hopefully should make it occur less.
I am closing this for now, but feel free to re-open the issue if you encounter that again.
