### ISSUE TITLE
Trouble with getting started

### ISSUE THREAD

**Issue by daneshvar-amrollahi** [secure-foundations/mariposa#19]
Hi,
I believe I have successfully installed Mariposa by following the Instruction steps in the README. For now, I am only testing the single query mode. According to the Quick Start section, a python script `main.py` is supposed to exist in the `src/` directory. However, this is not the case. So I tried `exper_wizard.py` instead, and received the following output:
```
$ python3 src/exper_wizard.py single -s z3_4_12_2 -i data/samples/single_check.smt2 --verbose 3 --clear-existing
[ERROR] gen/single_proj/ is not a directory
```
which is true. In `gen/`, I can only see `single/` and `single_mut/` and no `single_proj/`.

Could you please guide me on what is going wrong?

**Comment by yizhou7** [comment]
Thanks for bring this up. What is wrong is that I did not really expect other people to use this tool lol. I have made some changes and hopefully that fixes the issue. Please let me know if it does not.

**Comment by daneshvar-amrollahi** [comment]
It works now, thanks!
